upstream portfolio {
    server portfolio:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://portfolio;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /portfolio/staticfiles/;
    }
}

